"""add category table

Revision ID: 86f9b6df7df4
Revises: 947c1925c54d
Create Date: 2025-11-02 21:08:31.171497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86f9b6df7df4'
down_revision: Union[str, Sequence[str], None] = '947c1925c54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.add_column('expense', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_expense_category'), table_name='expense')
    op.create_foreign_key(None, 'expense', 'category', ['category_id'], ['id'])
    op.drop_column('expense', 'category')
    op.add_column('income', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_income_category'), table_name='income')
    op.create_foreign_key(None, 'income', 'category', ['category_id'], ['id'])
    op.drop_column('income', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.create_index(op.f('ix_income_category'), 'income', ['category'], unique=False)
    op.drop_column('income', 'category_id')
    op.add_column('expense', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.create_index(op.f('ix_expense_category'), 'expense', ['category'], unique=False)
    op.drop_column('expense', 'category_id')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###