"""update user and create income tables

Revision ID: bc7c66c80fba
Revises: 
Create Date: 2025-10-31 22:59:15.477251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc7c66c80fba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('income', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('income', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('income', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.add_column('income', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_income_category'), 'income', ['category'], unique=False)
    op.create_foreign_key(None, 'income', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_index(op.f('ix_income_category'), table_name='income')
    op.drop_column('income', 'user_id')
    op.drop_column('income', 'date_time')
    op.drop_column('income', 'description')
    op.drop_column('income', 'category')
    op.drop_column('income', 'amount')
    # ### end Alembic commands ###